// // context/LanguageContext.js
// // ─────────────────────────────────────────────────────────────────────────────
// // Language system that works OFFLINE by default.
// //
// // Priority order for translations:
// //   1. Hardcoded strings (instant, always available) ← PRIMARY
// //   2. API fetch (background only, updates cache if server is running)
// //
// // This means the app NEVER shows raw key names, never breaks without a server,
// // and still picks up live updates when the backend is reachable.
// // ─────────────────────────────────────────────────────────────────────────────

// import AsyncStorage from '@react-native-async-storage/async-storage';
// import React, {
//   createContext, useContext, useState, useCallback, useRef, useEffect,
// } from 'react';

// // ── Category → language mapping ───────────────────────────────────────────────
// // Categories are now age-group based (children/intermediate/youth/adult).
// // Language is selected independently and stored in state.
// // CATEGORY_LANG_MAP is no longer needed.

// // ── Full hardcoded translations ───────────────────────────────────────────────
// // These are the PRIMARY source. The app never needs the API to display text.
// const TRANSLATIONS = {
//   en: {
//     // Shared
//     back:               '‹  Back',
//     loading:            'Loading…',
//     retry:              'Retry',
//     noData:             'No data found.',
//     errorTitle:         'Something went wrong',
//     errorDefault:       'Unable to load content. Please try again.',
//     // Homescreen
//     orgName:            "THE GOSPEL FAITH MISSION INT'L.",
//     orgShort:           '( Gospelar )',
//     quarterlyTheme:     'QUARTERLY THEME',
//     beginLessons:       'Begin {label} Lessons',
//     switchCategory:     'Switch Category',
//     allCategories:      'ALL CATEGORIES',
//     footerOrg:          '© Gospelar Sunday School Department',
//     footerSite:         'www.gospelar.com',
//     selectCategory:     'SELECT CATEGORY',
//     darkMode:           '🌙  Dark Mode',
//     lightMode:          '☀️  Light Mode',
//     // SecondPage
//     quarterlyUnits:     'Quarterly Units',
//     unitsOfStudy:       'UNITS OF STUDY',
//     tapToOpen:          'Tap to open  ›',
//     unitsFooter:        'Select a unit to explore its lessons.',
//     unitCount:          '{n} Units',
//     // UnitLessonsPage
//     unitOfStudy:        'UNIT OF STUDY',
//     lessonsSection:     'LESSONS',
//     tapToStudy:         'Tap a lesson to begin studying.',
//     noLessons:          'No lessons found for this unit.',
//     lessonCount:        '{n} Lesson',
//     lessonCountPlural:  '{n} Lessons',
//     // LessonPage
//     lessonDetails:      'LESSON DETAILS',
//     lesson:             'LESSON',
//     suggestedHymns:     'Suggested Hymns',
//     devotionalReading:  'Devotional Reading',
//     adults:             'Adults',
//     youth:              'Youth',
//     intermediate:       'Intermediate',
//     scriptures:         'Scriptures',
//     memoryVerse:        'MEMORY VERSE',
//     background:         'BACKGROUND',
//     notesOnLesson:      'NOTES ON THE LESSON',
//     conclusion:         'CONCLUSION',
//     discussionQuestions:'DISCUSSION QUESTIONS',
//     responsibilityMonth:'RESPONSIBILITY MONTH',
//     quizFab:            'Quiz',
//     dailyReading:       'Daily\nReading',
//     readFullScreen:     'Read Full Screen',
//     partOf:             'Part {current} of {total}',
//     prev:               'Prev',
//     next:               'Next',
//     quizCompleted:      'Quiz Completed ✓',
//     takeQuiz:           'Take Quiz →',
//     loadingLesson:      'Loading lesson…',
//     topicFor:           'Topic — {group}',
//     best:               'BEST',
//     totalPts:           'TOTAL PTS',
//     yourRank:           'YOUR RANK',
//     returnsIn:          'Returns in',
//     todayScripture:     "TODAY'S SCRIPTURE",
//     verseInstruction:   'Read this passage in full before beginning your day.\nMeditate on it throughout the day and carry it with you.',
//     highlightPrompt:    'Highlight this',
//     removeHighlight:    'Remove highlight',
//     removeMsg:          'Remove this highlight?',
//     highlightMsg:       'Highlight this passage for easy reference.',
//     highlights:         '{n} Saved Highlight',
//     highlightsPlural:   '{n} Saved Highlights',
//     dayOf:              'Day {current} of {total}',
//     devotionalDays:     'Devotional Days',
//     prevDay:            'Prev',
//     nextDay:            'Next',
//     // Quiz lock screen
//     quizLockedTitle:    'Come Back Tomorrow!',
//     quizLockedSub:      "You've already completed this quiz today.",
//     quizLockedRule:     'One attempt per lesson per day.',
//     gotIt:              'Got it',
//     noQuizBody:         'No questions found for this lesson yet.',
//     checkBackSoon:      'Check back soon!',
//     finishSubmit:       'Finish & Submit',
//     // Notifications
//     notificationsTitle:     'Notifications',
//     pushNotifications:      'Push Notifications',
//     notifSubtitle:          'Choose what to be reminded about',
//     quizReminder:           'Quiz Reminder',
//     quizReminderSub:        'Daily reminder to take your lesson quiz',
//     devotionalReminder:     'Devotional Reminder',
//     devotionalReminderSub:  'Daily reminder for morning devotional reading',
//     reminderTime:           'Reminder Time',
//     setTime:                'Set Time',
//     notifEnabled:           'Enabled',
//     notifDisabled:          'Disabled',
//     notifPermissionTitle:   'Enable Notifications',
//     notifPermissionMsg:     'Allow Gospelar to send you daily reminders for quiz and devotional reading.',
//     notifPermissionDeny:    'Not Now',
//     notifPermissionAllow:   'Allow',
//     notifSaved:             'Reminder saved!',
//     notifCancelled:         'Reminder turned off',
//     quizNotifTitle:         '⚡  Quiz Time!',
//     quizNotifBody:          "Don't forget to take today's lesson quiz. Keep your streak going!",
//     devNotifTitle:          '📖  Daily Devotional',
//     devNotifBody:           "Start your day with God's Word. Your devotional reading is ready.",
//     notifHour:              'Hour',
//     notifMinute:            'Minute',
//     notifAM:                'AM',
//     notifPM:                'PM',
//     // Homescreen & CombinedUnitsPage UI
//     quarterPeriod:      'QUARTER PERIOD',
//     memoryScripture:    'MEMORY SCRIPTURE',
//     browseUnits:        'Browse Units',
//     categories:         'Categories',
//     viewAll:            'View all',
//     thisQuarter:        'This Quarter',
//     searchPlaceholder:  'Search lessons, topics…',
//     appearance:         'APPEARANCE',
//     language:           'LANGUAGE',
//     ageGroup:           'AGE GROUP',
//     noUnits:            'No units available.',
//     unitsLabel:         '{n} Unit',
//     unitsLabelPlural:   '{n} Units',
//     lessonsLabel:       '{n} Lesson',
//     lessonsLabelPlural: '{n} Lessons',
//     browseAllLessons:   'Browse all lessons',
//     // ProgressScreen
//     myProgress:          'My Progress',
//     myScores:            'My Scores',
//     leaderboard:         'Leaderboard',
//     lessonScores:        'Lesson Scores',
//     topLearners:         'Top Learners',
//     cumulativeBest:      'Cumulative best scores',
//     noQuizzesYet:        'No quizzes yet',
//     completeQuizToSee:   'Complete a lesson quiz to see your scores.',
//     startStudying:       'Start Studying',
//     noScoresYet:         'No scores yet',
//     beFirstQuiz:         'Be the first to complete a quiz!',
//     // Common navigation labels
//     home:                'Home',
//     progress:            'Progress',
//     settings:            'Settings',
//     lessons:             'Lessons',
//     read:                'Read',
//     saved:               'Saved',
//     done:                'Done',
//     points:              'Points',
//     rank:                'Rank',
//     // Categories (age groups)
//     cat_children:       'Children',
//     cat_children_short: 'Children',
//     cat_children_hero:  'Fun lessons\nfor little hearts\nof faith',
//     cat_children_cta:   'Explore Now',
//     cat_children_tag:   'CHILDREN',
//     cat_intermediate:   'Intermediate',
//     cat_intermediate_short: 'Intermediate',
//     cat_intermediate_hero: 'Building a strong\nfoundation\nin God\'s Word',
//     cat_intermediate_cta: 'Start Learning',
//     cat_intermediate_tag: 'INTERMEDIATE',
//     cat_youth:          'Youth',
//     cat_youth_short:    'Youth',
//     cat_youth_hero:     'Equipping the\nnext generation\nof believers',
//     cat_youth_cta:      'Join Now',
//     cat_youth_tag:      'YOUTH',
//     cat_adult:          'Adult',
//     cat_adult_short:    'Adult',
//     cat_adult_hero:     'Start your\nspiritual journey\ntoday',
//     cat_adult_cta:      'Begin Lessons',
//     cat_adult_tag:      'ADULT',
//     cat_quarter:        '4TH QUARTER • JUN – AUG 2026',
//     cat_lessons13:      '13 Lessons',
//     quizCtaTitle:       'Take the Lesson Quiz',
//     quizCtaSub:         'Test your knowledge · earn points · join the leaderboard',
//     // Hymn Modal
//     suggestedHymnsTitle:'Suggested Hymns',
//     hymnsForLesson:     '{n} hymn for this lesson',
//     hymnsForLessonPlural:'{n} hymns for this lesson',
//     hymnInstructions:   'These hymns complement the lesson theme. Lead the congregation in singing before or after the study.',
//     tapToViewHymn:      'Tap to view full hymn',
//     hymnVerse:          '🎵  Sing to the Lord a new song; sing to the Lord, all the earth.',
//     hymnVerseRef:       '— Psalm 96:1',
//     // Devotional Modal
//     dailyDevotional:    'Daily Devotional',
//     devotionalBanner:   '"Your word is a lamp to my feet and a light to my path."',
//     devotionalRef:      'Psalm 119:105',
//     // Quiz Modal
//     lessonQuiz:         'Lesson Quiz',
//     loadingQuiz:        'Loading quiz questions…',
//     noQuizTitle:        'No Quiz Available',
//     noQuizSub:          'There is no quiz set for this lesson yet.\nCheck back soon!',
//     questionOf:         'Question {current} of {total}',
//     pts:                '{n} pts',
//     nextQuestion:       'Next Question',
//     seeResults:         'See Results',
//     correctFeedback:    'Correct! Well done.',
//     wrongFeedback:      'Correct answer: {letter}. {answer}',
//     scoreSaved:         'Score saved to leaderboard!',
//     savingScore:        'Saving your score…',
//     saveError:          'Could not save score.',
//     retryQuiz:          'Retry Quiz',
//     done:               'Done',
//     excellent:          'Excellent!',
//     wellDone:           'Well Done!',
//     keepStudying:       'Keep Studying!',
//     tryAgain:           'Try Again!',
//     // DevotionalReadingScreen
//     openingPrayer:      'Opening Prayer',
//     reflection:         'Reflection',
//     application:        'Application',
//     highlighted:        'Highlighted',
//     noHighlights:       'Long-press any paragraph to highlight and save it for later.',
//     savedHighlights:    'SAVED HIGHLIGHTS',
//     clearAll:           'Clear All',
//     cancel:             'Cancel',
//     doHighlight:        '🖊  Highlight',
//     doRemove:           '🗑  Remove',
//   },

//   yo: {
//     // Shared
//     back:               '‹  Padà',
//     loading:            'Ń gbé…',
//     retry:              'Gbìyànjú Lẹ́ẹ̀kan Sí',
//     noData:             'Kò sí ìsọfúnni.',
//     errorTitle:         'Àṣìṣe kan ṣẹlẹ̀',
//     errorDefault:       'A kò lè gbé ìkókò. Jọwọ gbìyànjú lẹ́ẹ̀kan sí.',
//     // Homescreen
//     orgName:            "ÌGBÀGBỌ́ ÌHÌNRẸ̀RẸ̀ AGBÁYÉ INT'L.",
//     orgShort:           '( Gospelar )',
//     quarterlyTheme:     'ÀKỌLÉ ÌMẸ́TA OSÙ',
//     beginLessons:       'Bẹ̀rẹ̀ Ẹ̀kọ́ {label}',
//     switchCategory:     'Yí Ẹ̀ka Padà',
//     allCategories:      'GBOGBO ẸÈ̀KA',
//     footerOrg:          '© Ẹ̀ka Ilé-ẹ̀kọ́ Ọjọ́ Àhọ́ Gospelar',
//     footerSite:         'www.gospelar.com',
//     selectCategory:     'YAN ẸÈ̀KA',
//     darkMode:           '🌙  Ìpele Òkunkun',
//     lightMode:          '☀️  Ìpele Ìmọ́lẹ̀',
//     // SecondPage
//     quarterlyUnits:     'Àwọn Ẹ̀ka Ìmẹ́ta Oṣù',
//     unitsOfStudy:       'ÀWỌN ẸÈ̀KA ẸÈ̀KỌ́',
//     tapToOpen:          'Tẹ láti ṣí  ›',
//     unitsFooter:        'Yan ẹ̀ka kan láti ṣàwárí àwọn ẹ̀kọ́ rẹ̀.',
//     unitCount:          'Ẹ̀ka {n}',
//     // UnitLessonsPage
//     unitOfStudy:        'ẸÈ̀KA ẸÈ̀KỌ́',
//     lessonsSection:     'ÀWỌN ẸÈ̀KỌ́',
//     tapToStudy:         'Tẹ ẹ̀kọ́ kan láti bẹ̀rẹ̀ ìkẹ́kọ̀ọ́.',
//     noLessons:          'Kò sí ẹ̀kọ́ fun ẹ̀ka yìí.',
//     lessonCount:        'Ẹ̀kọ́ {n}',
//     lessonCountPlural:  'Àwọn Ẹ̀kọ́ {n}',
//     // LessonPage
//     lessonDetails:      'ÀLÀYÉ ẸÈ̀KỌ́',
//     lesson:             'ẸÈ̀KỌ́',
//     suggestedHymns:     'Àwọn Orin Ìdánimọ̀',
//     devotionalReading:  'Kíkà Ìfọkànsin',
//     adults:             'Àgbàlagbà',
//     youth:              'Ọ̀dọ́',
//     intermediate:       'Àárín',
//     scriptures:         'Àwọn Ìwé Mímọ́',
//     memoryVerse:        'ẸSẸ̀ ÌRÁNTÍ',
//     background:         'ÌPÌLẸ̀ṢẸ̀',
//     notesOnLesson:      'ÀWỌN ÀKỌSÍLẸ̀ ẸÈ̀KỌ́',
//     conclusion:         'ÌPARÍ',
//     discussionQuestions:'ÀWỌN ÌBÉÈRÈ ÌJÍRÒRÒ',
//     responsibilityMonth:'OṢÙN OJÚṢE',
//     quizFab:            'Ìdánwò',
//     dailyReading:       'Kíkà\nỌjọ́ Kan',
//     // Quiz lock screen
//     quizLockedTitle:    'Come Back Tomorrow!',
//     quizLockedSub:      "You've already completed this quiz today.",
//     quizLockedRule:     'One attempt per lesson per day.',
//     gotIt:              'Got it',
//     noQuizBody:         'No questions found for this lesson yet.',
//     checkBackSoon:      'Check back soon!',
//     finishSubmit:       'Finish & Submit',
//     readFullScreen:     'Ka ni Iboju Kikun',
//     partOf:             'Apá {current} nínú {total}',
//     prev:               'Ṣáájú',
//     next:               'Tókàn',
//     quizCompleted:      'Ìdánwò Parí ✓',
//     takeQuiz:           'Ṣe Ìdánwò →',
//     loadingLesson:      'Ń gbé ẹ̀kọ́…',
//     topicFor:           'Àkọlé — {group}',
//     best:               'TI O DARA JU',
//     totalPts:           'ÀPAPỌ̀ ÀMÌ',
//     yourRank:           'IPÒ RẸWỌ',
//     returnsIn:          'Padà wá ní',
//     todayScripture:     'ẸSẸ̀ ỌJỌONI',
//     verseInstruction:   'Ka ìgbẹ̀yìn yìí ní kíkún ṣáájú kí o bẹ̀rẹ̀ ọjọ́ rẹ.\nRonu lórí rẹ̀ ní gbogbo ọjọ́ kí o sì gbé e lọ pẹ̀lú rẹ.',
//     highlightPrompt:    'Samisi Rẹ̀',
//     removeHighlight:    'Yọ Àmì Kúrò',
//     removeMsg:          'Yọ àmì yìí kúrò?',
//     highlightMsg:       'Samisi ìgbẹ̀yìn yìí fún ìtọ́kasí irọlẹ.',
//     highlights:         'Àmì {n} Tí A Pamọ́',
//     highlightsPlural:   'Àwọn Àmì {n} Tí A Pamọ́',
//     dayOf:              'Ọjọ́ {current} nínú {total}',
//     devotionalDays:     'Àwọn Ọjọ́ Ìfọkànsin',
//     prevDay:            'Ṣáájú',
//     nextDay:            'Tókàn',
//     // Quiz lock
//     quizLockedTitle:    'Padà wá Ọla!',
//     quizLockedSub:      'O ti parí ìdánwò yìí lónìí.',
//     quizLockedRule:     'Ìgbìyànjú kan ní ẹ̀kọ́ kan lójúmọ́.',
//     gotIt:              'Mò',
//     noQuizBody:         'Kò sí àwọn ìbéèrè fún ẹ̀kọ́ yìí.',
//     checkBackSoon:      'Padà wá lẹ́yìn náà!',
//     finishSubmit:       'Parí kí o sì Fisilẹ̀',
//     // Notifications
//     notificationsTitle:     'Àwọn Ìfítónilétí',
//     pushNotifications:      'Ìfítónilétí Tìtẹ',
//     notifSubtitle:          'Yan ohun tí o fẹ́ rántí',
//     quizReminder:           'Ìfítónilétí Ìdánwò',
//     quizReminderSub:        'Ìfítónilétí ojoojúmọ́ fún ìdánwò ẹ̀kọ́',
//     devotionalReminder:     'Ìfítónilétí Ìfọkànsin',
//     devotionalReminderSub:  'Ìfítónilétí ojoojúmọ́ fún ìfọkànsin òwúrọ̀',
//     reminderTime:           'Àkókò Ìfítónilétí',
//     setTime:                'Tò Àkókò',
//     notifEnabled:           'Ní Ìṣiṣẹ́',
//     notifDisabled:          'Kò Ṣiṣẹ́',
//     notifPermissionTitle:   'Ṣe Àwọn Ìfítónilétí',
//     notifPermissionMsg:     'Jẹ́ kí Gospelar rán ọ lọ́wọ́ pẹ̀lú àwọn ìfítónilétí ojoojúmọ́.',
//     notifPermissionDeny:    'Kì í ṣe Nísinsin yìí',
//     notifPermissionAllow:   'Gbà',
//     notifSaved:             'Ìfítónilétí fipamọ́!',
//     notifCancelled:         'Ìfítónilétí paa',
//     quizNotifTitle:         '⚡  Àkókò Ìdánwò!',
//     quizNotifBody:          'Má gbàgbé láti ṣe ìdánwò ẹ̀kọ́ òní. Máa tẹ̀síwájú!',
//     devNotifTitle:          '📖  Ìfọkànsin Ojoojúmọ́',
//     devNotifBody:           'Bẹ̀rẹ̀ ọjọ́ rẹ pẹ̀lú Ọ̀rọ̀ Ọlọ́run. Ìfọkànsin rẹ ṣetan.',
//     notifHour:              'Wákàtí',
//     notifMinute:            'Ìṣẹ́jú',
//     notifAM:                'AM',
//     notifPM:                'PM',
//     // Notifications
//     notificationsTitle:     'Ọkwa',
//     pushNotifications:      'Ọkwa Nntụpụ',
//     notifSubtitle:          'Họọrọ ihe ị chọọ ka a chetara gị',
//     quizReminder:           'Ncheta Ule',
//     quizReminderSub:        'Ncheta kwa ụbọchị maka ule mmụta',
//     devotionalReminder:     'Ncheta Ofufe',
//     devotionalReminderSub:  'Ncheta kwa ụbọchị maka ọgụgụ ofufe ụtụtụ',
//     reminderTime:           'Oge Ncheta',
//     setTime:                'Tọọ Oge',
//     notifEnabled:           'Na-arụ ọrụ',
//     notifDisabled:          'Anaghị arụ ọrụ',
//     notifPermissionTitle:   'Nọdoo Ọkwa',
//     notifPermissionMsg:     'Kwe ka Gospelar zipu gị ndetu kwa ụbọchị.',
//     notifPermissionDeny:    'Ugbu a Ọ dịghị',
//     notifPermissionAllow:   'Kwere',
//     notifSaved:             'Ncheta echekwara!',
//     notifCancelled:         'Ncheta kagburu',
//     quizNotifTitle:         '⚡  Oge Ule!',
//     quizNotifBody:          'Echefula ime ule mmụta taa. Nọgide na-aga n\'ihu!',
//     devNotifTitle:          '📖  Ofufe Ụbọchị',
//     devNotifBody:           'Bido ụbọchị gị na Okwu Chineke. Ọgụgụ ofufe gị dị njikere.',
//     notifHour:              'Elekere',
//     notifMinute:            'Nkeji',
//     notifAM:                'AM',
//     notifPM:                'PM',
//     // Notifications
//     notificationsTitle:     'Sanarwa',
//     pushNotifications:      'Sanarwar Tunkude',
//     notifSubtitle:          'Zaɓi abin da za a tuna maka',
//     quizReminder:           'Tunawa da Jarrabawa',
//     quizReminderSub:        'Tunawa kowace rana don jarrabawar darasi',
//     devotionalReminder:     'Tunawa da Ibada',
//     devotionalReminderSub:  'Tunawa kowace rana don karatu na ibada na safe',
//     reminderTime:           'Lokacin Tunawa',
//     setTime:                'Saita Lokaci',
//     notifEnabled:           'An Kunna',
//     notifDisabled:          'An Kashe',
//     notifPermissionTitle:   'Kunna Sanarwa',
//     notifPermissionMsg:     'Bari Gospelar ya aiko maka tunatarwa kowace rana.',
//     notifPermissionDeny:    'Ba Yanzu',
//     notifPermissionAllow:   'Yarda',
//     notifSaved:             'An adana tunawa!',
//     notifCancelled:         'An kashe tunawa',
//     quizNotifTitle:         '⚡  Lokacin Jarrabawa!',
//     quizNotifBody:          'Kar ka manta yin jarrabawar darasi na yau. Ci gaba da kokari!',
//     devNotifTitle:          '📖  Ibada ta Yau',
//     devNotifBody:           'Fara ranarku da Maganar Allah. Karatu na ibada yana shirye.',
//     notifHour:              'Awa',
//     notifMinute:            'Minti',
//     notifAM:                'AM',
//     notifPM:                'PM',
//     // Homescreen & CombinedUnitsPage
//     quarterPeriod:      'ÀKÓKÒ ÌMẸ́TA OSÙ',
//     memoryScripture:    'ẸSẸ̀ ÌRÁNTÍ',
//     browseUnits:        'Ṣàwárí Àwọn Ẹ̀ka',
//     categories:         'Àwọn Ẹ̀yà',
//     viewAll:            'Wo gbogbo',
//     thisQuarter:        'Ìmẹ́ta Osù Yìí',
//     searchPlaceholder:  'Ṣàwárí àwọn ẹ̀kọ́, àwọn àkọlé…',
//     appearance:         'ÌWÒ ÀPÒ',
//     language:           'ÈDÈ',
//     ageGroup:           'ẸGBẸ́ ỌJỌÓ-ORI',
//     noUnits:            'Kò sí àwọn ẹ̀ka.',
//     unitsLabel:         'Ẹ̀ka {n}',
//     unitsLabelPlural:   'Àwọn Ẹ̀ka {n}',
//     lessonsLabel:       'Ẹ̀kọ́ {n}',
//     lessonsLabelPlural: 'Àwọn Ẹ̀kọ́ {n}',
//     browseAllLessons:   'Wo gbogbo àwọn ẹ̀kọ́',
//     // ProgressScreen
//     myProgress:          'Ìlọsíwájú Mi',
//     myScores:            'Àwọn Àmì Mi',
//     leaderboard:         'Àkọsílẹ̀ Àgbára',
//     lessonScores:        'Àwọn Àmì Ẹ̀kọ́',
//     topLearners:         'Àwọn Akẹ́kọ̀ọ́ Àgbà',
//     cumulativeBest:      'Àwọn àmì tó dára jù',
//     noQuizzesYet:        'Kò sí ìdánwò títí di ìsinsìnyí',
//     completeQuizToSee:   'Parí ìdánwò ẹ̀kọ́ kan láti rí àwọn àmì rẹ.',
//     startStudying:       'Bẹ̀rẹ̀ Ìkẹ́kọ̀ọ́',
//     noScoresYet:         'Kò sí àmì títí di ìsinsìnyí',
//     beFirstQuiz:         'Jẹ́ èkíní láti parí ìdánwò!',
//     home:                'Ilé',
//     progress:            'Ìlọsíwájú',
//     settings:            'Ètò',
//     lessons:             'Àwọn Ẹ̀kọ́',
//     read:                'Kà',
//     saved:               'Fipamọ́',
//     done:                'Parí',
//     points:              'Àwọn Àmì',
//     rank:                'Ipò',
//     // Categories
//     cat_children:       'Àwọn Ọmọ',
//     cat_children_short: 'Ọmọ',
//     cat_children_hero:  'Àwọn ẹ̀kọ́ ìdárayá\nfún àwọn ọkàn kéékéké\ntí ó ní ìgbàgbọ́',
//     cat_children_cta:   'Ṣàwárí Rẹ̀',
//     cat_children_tag:   'ÀWỌN ỌMỌ',
//     cat_intermediate:   'Àárín-Ọjọ́-Orí',
//     cat_intermediate_short: 'Àárín',
//     cat_intermediate_hero: 'Kíkọ́ ìpìlẹ̀ṣẹ̀ tó lágbára\nnínu Ọ̀rọ̀ Ọlọ́run',
//     cat_intermediate_cta: 'Bẹ̀rẹ̀ Ẹ̀kọ́',
//     cat_intermediate_tag: 'ÀÁRÍN',
//     cat_youth:          'Ọ̀dọ́',
//     cat_youth_short:    'Ọ̀dọ́',
//     cat_youth_hero:     'Ìmúrasílẹ̀ ìran\ọ̀dọ́ tó ń bọ̀\nfún Ọlọ́run',
//     cat_youth_cta:      'Darapọ̀ Mọ́',
//     cat_youth_tag:      'ỌDỌ́',
//     cat_adult:          'Àgbàlagbà',
//     cat_adult_short:    'Àgbàlagbà',
//     cat_adult_hero:     'Bẹ̀rẹ̀ ìrìnàjò\nẹ̀mí rẹ\nní òní',
//     cat_adult_cta:      'Bẹ̀rẹ̀ Ẹ̀kọ́',
//     cat_adult_tag:      'ÀGBÀLAGBÀ',
//     cat_quarter:        'ÌDÁ-MẸ́RIN KẸRIN • ÒṢÙ 4 – 8 2026',
//     cat_lessons13:      'Ẹ̀kọ́ 13',
//     quizCtaTitle:       'Ṣe Ìdánwò Ẹ̀kọ́',
//     quizCtaSub:         'Ṣe ìdánwò · gba àwọn àmì · darapọ̀ mọ́ àkọsílẹ̀',
//     // Hymn Modal
//     suggestedHymnsTitle:'Àwọn Orin Ìdánimọ̀',
//     hymnsForLesson:     'Orin {n} fún ẹ̀kọ́ yìí',
//     hymnsForLessonPlural:'Àwọn orin {n} fún ẹ̀kọ́ yìí',
//     hymnInstructions:   'Àwọn orin wọ̀nyí jẹ́ àfikún sí àkọlé ẹ̀kọ́.',
//     tapToViewHymn:      'Tẹ láti wo orin kún',
//     hymnVerse:          '🎵  Kọrin orin tuntun fún Olúwa; kọrin fún Olúwa, gbogbo ilẹ̀.',
//     hymnVerseRef:       '— Orin Dáfídì 96:1',
//     // Devotional Modal
//     dailyDevotional:    'Ìfọkànsin Ọjọ́ Kan',
//     devotionalBanner:   '"Ọ̀rọ̀ Rẹ jẹ́ ìmọ́lẹ̀ sí ẹsẹ̀ mi, àti ìtọ́nà sí ọnà mi."',
//     devotionalRef:      'Orin Dáfídì 119:105',
//     // Quiz Modal
//     lessonQuiz:         'Ìdánwò Ẹ̀kọ́',
//     loadingQuiz:        'Ń gbé àwọn ìbéèrè ìdánwò…',
//     noQuizTitle:        'Kò Sí Ìdánwò',
//     noQuizSub:          'Kò sí ìdánwò fún ẹ̀kọ́ yìí.\nẸ padà wá lẹ́yìn náà!',
//     questionOf:         'Ìbéèrè {current} nínú {total}',
//     pts:                'Àmì {n}',
//     nextQuestion:       'Ìbéèrè Tókàn',
//     seeResults:         'Wo Àbájáde',
//     correctFeedback:    'Ó tọ́! Ṣe dáadáa.',
//     wrongFeedback:      'Ìdáhùn tó tọ́: {letter}. {answer}',
//     scoreSaved:         'À tí tọ́jú àmì rẹ!',
//     savingScore:        'Ń tọ́jú àmì rẹ…',
//     saveError:          'A kò lè tọ́jú àmì rẹ.',
//     retryQuiz:          'Tún Ìdánwò Ṣe',
//     done:               'Parí',
//     excellent:          'Ó Dára Gan!',
//     wellDone:           'Ṣe Dáadáa!',
//     keepStudying:       'Máa Kẹ́kọ̀ọ́!',
//     tryAgain:           'Gbìyànjú Lẹ́ẹ̀kan Sí!',
//     // DevotionalReadingScreen
//     openingPrayer:      'Adura Ìṣíjú',
//     reflection:         'Ìrò̩lẹ̀ Ọkàn',
//     application:        'Ìlò',
//     highlighted:        'Àmì Lé Sí',
//     noHighlights:       'Tẹ àpínrọ̀ eyíkeyí títí láti fi àmì sí i tọ́jú rẹ̀.',
//     savedHighlights:    'ÀWỌN ÀMÌ TÓ TÍ TỌ́JÚ',
//     clearAll:           'Paarẹ Gbogbo',
//     cancel:             'Fagilé',
//     doHighlight:        '🖊  Ṣe Àmì',
//     doRemove:           '🗑  Yọ Kúrò',
//   },

//   // ── IGBO ──────────────────────────────────────────────────────────────────
//   ig: {
//     // Shared
//     back:               '‹  Laghachi',
//     loading:            'Na-ebugharị…',
//     retry:              'Nwaa ọzọ',
//     noData:             'Enweghị data.',
//     errorTitle:         'Ihe ọjọọ mere',
//     errorDefault:       'Enweghị ike ibugo ọdịnaya. Biko nwaa ọzọ.',
//     // Homescreen
//     orgName:            "GOSPEL FAITH MISSION INT'L.",
//     orgShort:           '( Gospelar )',
//     quarterlyTheme:     'ISIOKWU ỌNWA ATỌ',
//     beginLessons:       'Bido Mmụta {label}',
//     switchCategory:     'Gbanwee Udi',
//     allCategories:      'ỤDỊ NIILE',
//     footerOrg:          '© Ngalaba Ulo Akwukwo Ụbọchị Izu Uka Gospelar',
//     footerSite:         'www.gospelar.com',
//     selectCategory:     'HỌỌRỌ UDI',
//     darkMode:           '🌙  Ọnọdụ Ọchịchọ',
//     lightMode:          '☀️  Ọnọdụ Ìmụm̀ụ',
//     // SecondPage
//     quarterlyUnits:     'Njikọ Ọnwa Atọ',
//     unitsOfStudy:       'NJIKỌ MMỤTA',
//     tapToOpen:          'Pịa iji mepee  ›',
//     unitsFooter:        'Họọrọ njikọ iji chọpụta mmụta ya.',
//     unitCount:          'Njikọ {n}',
//     // UnitLessonsPage
//     unitOfStudy:        'NJIKỌ MMỤTA',
//     lessonsSection:     'MMỤTA',
//     tapToStudy:         'Pịa mmụta iji bido ọmụmụ.',
//     noLessons:          'Enweghị mmụta maka njikọ a.',
//     lessonCount:        'Mmụta {n}',
//     lessonCountPlural:  'Mmụta {n}',
//     // LessonPage
//     lessonDetails:      'NKỌWA MMỤTA',
//     lesson:             'MMỤTA',
//     suggestedHymns:     'Abụ Ekwenyere',
//     devotionalReading:  'Ọgụgụ Ofufe',
//     adults:             'Ndọrọndọrọ',
//     youth:              'Ọchịchọ',
//     intermediate:       'Etiti',
//     scriptures:         'Akwụkwọ Nsọ',
//     memoryVerse:        'EDEMEDE NCHETA',
//     background:         'IHE MERE N\'IHU',
//     notesOnLesson:      'NDEKỌ N\'IMU AJA',
//     conclusion:         'NJEDEBE',
//     discussionQuestions:'AJỤJỤ NNỌCHITE',
//     responsibilityMonth:'ỌNWA ỌRỤ',
//     quizFab:            'Ule',
//     dailyReading:       'Ọgụgụ\nỤbọchị',
//     // Quiz lock screen
//     quizLockedTitle:    'Come Back Tomorrow!',
//     quizLockedSub:      "You've already completed this quiz today.",
//     quizLockedRule:     'One attempt per lesson per day.',
//     gotIt:              'Got it',
//     noQuizBody:         'No questions found for this lesson yet.',
//     checkBackSoon:      'Check back soon!',
//     finishSubmit:       'Finish & Submit',
//     readFullScreen:     'Gụọ Oghere Oke',
//     partOf:             'Akụkụ {current} n\'ime {total}',
//     prev:               'Gara Aga',
//     next:               'Nke Ọzọ',
//     quizCompleted:      'Ule Emechara ✓',
//     takeQuiz:           'Nwaa Ule →',
//     loadingLesson:      'Na-ebugharị mmụta…',
//     topicFor:           'Isiokwu — {group}',
//     best:               'KACHA MMA',
//     totalPts:           'NTỌALA NIILE',
//     yourRank:           'ỌKWA GỊ',
//     returnsIn:          'Ọ laghachiri na',
//     todayScripture:     'AKWỤKWỌ NSỌ NDI TATA',
//     verseInstruction:   'Gụọ okenye a nke ọma tupu ị malite ụbọchị gị.\nCheekwa ya n\'obi gị n\'ime ụbọchị nile.',
//     highlightPrompt:    'Tinye Akara',
//     removeHighlight:    'Wepu Akara',
//     removeMsg:          'Wepu akara a?',
//     highlightMsg:       'Tinye akara n\'okenye a maka ntụaka dị mfe.',
//     highlights:         'Akara {n} Echekwara',
//     highlightsPlural:   'Akara {n} Echekwara',
//     dayOf:              'Ụbọchị {current} n\'ime {total}',
//     devotionalDays:     'Ụbọchị Ofufe',
//     prevDay:            'Gara Aga',
//     nextDay:            'Nke Ọzọ',
//     // Quiz lock
//     quizLockedTitle:    'Laghachi Echi!',
//     quizLockedSub:      'Ị mechara ule a taa.',
//     quizLockedRule:     'Otu ọ bụla kwa ụbọchị maka ule.',
//     gotIt:              'Atọtụrụ',
//     noQuizBody:         'Enweghị ajụjụ maka mmụta a.',
//     checkBackSoon:      'Laghachi ma ọ dị mma!',
//     finishSubmit:       'Mechaa ma Zipu',
//     // Notifications
//     notificationsTitle:     'Ọkwa',
//     pushNotifications:      'Ọkwa Nntụpụ',
//     notifSubtitle:          'Họọrọ ihe ị chọọ ka a chetara gị',
//     quizReminder:           'Ncheta Ule',
//     quizReminderSub:        'Ncheta kwa ụbọchị maka ule mmụta',
//     devotionalReminder:     'Ncheta Ofufe',
//     devotionalReminderSub:  'Ncheta kwa ụbọchị maka ọgụgụ ofufe ụtụtụ',
//     reminderTime:           'Oge Ncheta',
//     setTime:                'Tọọ Oge',
//     notifEnabled:           'Na-arụ ọrụ',
//     notifDisabled:          'Anaghị arụ ọrụ',
//     notifPermissionTitle:   'Nọdoo Ọkwa',
//     notifPermissionMsg:     'Kwe ka Gospelar zipu gị ndetu kwa ụbọchị.',
//     notifPermissionDeny:    'Ugbu a Ọ dịghị',
//     notifPermissionAllow:   'Kwere',
//     notifSaved:             'Ncheta echekwara!',
//     notifCancelled:         'Ncheta kagburu',
//     quizNotifTitle:         '⚡  Oge Ule!',
//     quizNotifBody:          "Echefula ime ule mmụta taa. Nọgide na-aga n'ihu!",
//     devNotifTitle:          '📖  Ofufe Ụbọchị',
//     devNotifBody:           'Bido ụbọchị gị na Okwu Chineke. Ọgụgụ ofufe gị dị njikere.',
//     notifHour:              'Elekere',
//     notifMinute:            'Nkeji',
//     notifAM:                'AM',
//     notifPM:                'PM',
//     // Homescreen & CombinedUnitsPage
//     quarterPeriod:      'ỌNWA ATỌ ỌNỌDỤ',
//     memoryScripture:    'EDEMEDE NCHETA',
//     browseUnits:        'Chọpụta Njikọ',
//     categories:         'Ụdị',
//     viewAll:            'Hụ niile',
//     thisQuarter:        'Ọnwa Atọ A',
//     searchPlaceholder:  'Chọọ mmụta, isiokwu…',
//     appearance:         'ỌDỊDỊ',
//     language:           'ASỤSỤ',
//     ageGroup:           'ODI AGE',
//     noUnits:            'Enweghị njikọ ọ bụla.',
//     unitsLabel:         'Njikọ {n}',
//     unitsLabelPlural:   'Njikọ {n}',
//     lessonsLabel:       'Mmụta {n}',
//     lessonsLabelPlural: 'Mmụta {n}',
//     browseAllLessons:   'Hụ mmụta niile',
//     // ProgressScreen
//     myProgress:          'Ọganihu M',
//     myScores:            'Ntọala M',
//     leaderboard:         'Ndepụta Ndị Ọkachamara',
//     lessonScores:        'Ntọala Mmụta',
//     topLearners:         'Ndị Ọmụmụ Kacha Mma',
//     cumulativeBest:      'Ntọala kacha mma jikọtara',
//     noQuizzesYet:        'Enweghị ule ọ bụla',
//     completeQuizToSee:   'Mechaa ule mmụta iji hụ ntọala gị.',
//     startStudying:       'Bido Ọmụmụ',
//     noScoresYet:         'Enweghị ntọala ọ bụla',
//     beFirstQuiz:         'Bụrụ nke mbụ imechi ule!',
//     home:                'Ụlọ',
//     progress:            'Ọganihu',
//     settings:            'Ntọ',
//     lessons:             'Mmụta',
//     read:                'Gụọ',
//     saved:               'Echekwara',
//     done:                'Emechara',
//     points:              'Ntọala',
//     rank:                'Ọkwa',
//     // Categories
//     cat_children:       'Ụmụaka',
//     cat_children_short: 'Ụmụaka',
//     cat_children_hero:  'Mmụta vui\nmaka obi nta\nna-ekele Chukwu',
//     cat_children_cta:   'Chọpụta Ugbu a',
//     cat_children_tag:   'ỤMỤAKA',
//     cat_intermediate:   'Etiti',
//     cat_intermediate_short: 'Etiti',
//     cat_intermediate_hero: 'Iwu ọkwa ike\nn\'okwu Chukwu',
//     cat_intermediate_cta: 'Bido Ọmụmụ',
//     cat_intermediate_tag: 'ETITI',
//     cat_youth:          'Ọchịchọ',
//     cat_youth_short:    'Ọchịchọ',
//     cat_youth_hero:     'Ịkwado ọchịchọ\nnke ọzọ\nmaka Chukwu',
//     cat_youth_cta:      'Sonye Ugbu a',
//     cat_youth_tag:      'ỌCHỊCHỌ',
//     cat_adult:          'Ndọrọndọrọ',
//     cat_adult_short:    'Okenye',
//     cat_adult_hero:     'Bido ije ụzọ\nmara nke ọma\nn\'ụbọchị taa',
//     cat_adult_cta:      'Bido Mmụta',
//     cat_adult_tag:      'OKENYE',
//     cat_quarter:        'OKE NKE ANỌ • ỌNỌ 4 – 8 2026',
//     cat_lessons13:      'Mmụta 13',
//     quizCtaTitle:       'Nwaa Ule Mmụta',
//     quizCtaSub:         'Nwaa ihe ọmụmụ gị · nweta ntọala · sonye ndepụta',
//     // Hymn Modal
//     suggestedHymnsTitle:'Abụ Ekwenyere',
//     hymnsForLesson:     'Abụ {n} maka mmụta a',
//     hymnsForLessonPlural:'Abụ {n} maka mmụta a',
//     hymnInstructions:   'Abụ ndị a na-agbakwunye isiokwu mmụta.',
//     tapToViewHymn:      'Pịa iji hụ abụ',
//     hymnVerse:          '🎵  Bụọ Onyenwe anyị abụ ọhụrụ; bụọ Ya abụ, ala nile.',
//     hymnVerseRef:       '— Psalm 96:1',
//     // Devotional Modal
//     dailyDevotional:    'Ofufe Ụbọchị',
//     devotionalBanner:   '"Okwu Gị bụ ọgụgụ na ụkwụ m, na ọrụ n\'ụzọ m."',
//     devotionalRef:      'Psalm 119:105',
//     // Quiz Modal
//     lessonQuiz:         'Ule Mmụta',
//     loadingQuiz:        'Na-ebugharị ajụjụ ule…',
//     noQuizTitle:        'Enweghị Ule',
//     noQuizSub:          'Enweghị ule maka mmụta a.\nLaghachi ma ọ dị mma!',
//     questionOf:         'Ajụjụ {current} n\'ime {total}',
//     pts:                'Ntọala {n}',
//     nextQuestion:       'Ajụjụ Ọzọ',
//     seeResults:         'Hụ Nsonaazụ',
//     correctFeedback:    'Ọ dị mma! Ị mere nke ọma.',
//     wrongFeedback:      'Azịza ziri ezi: {letter}. {answer}',
//     scoreSaved:         'Ntọala gị echekwara!',
//     savingScore:        'Na-echekwa ntọala gị…',
//     saveError:          'Enweghị ike ichekwa ntọala gị.',
//     retryQuiz:          'Nwaa Ule Ọzọ',
//     done:               'Ọ Gwụọla',
//     excellent:          'Ọ Dị Mma Nke Ukwu!',
//     wellDone:           'Ị Mere Nke Ọma!',
//     keepStudying:       'Nọgide N\'ọmụmụ!',
//     tryAgain:           'Nwaa Ọzọ!',
//     // DevotionalReadingScreen
//     openingPrayer:      'Ekpere Mmalite',
//     reflection:         'Iche Uche',
//     application:        'Itinye Aka',
//     highlighted:        'Etinyere Akara',
//     noHighlights:       'Pịa nke ọ bụla ogologo oge iji tinye akara chekwaa ya.',
//     savedHighlights:    'AKARA ECHEKWARA',
//     clearAll:           'Hichapụ Nile',
//     cancel:             'Kagbuo',
//     doHighlight:        '🖊  Tinye Akara',
//     doRemove:           '🗑  Wepu',
//   },

//   // ── HAUSA ─────────────────────────────────────────────────────────────────
//   ha: {
//     // Shared
//     back:               '‹  Koma',
//     loading:            'Ana lodi…',
//     retry:              'Sake gwada',
//     noData:             'Babu bayani.',
//     errorTitle:         'Wani abu ya faru',
//     errorDefault:       'Ba a iya lodi abubuwa. Don Allah sake gwada.',
//     // Homescreen
//     orgName:            "GOSPEL FAITH MISSION INT'L.",
//     orgShort:           '( Gospelar )',
//     quarterlyTheme:     'TAKEN WATANNI UKU',
//     beginLessons:       'Fara Darasi {label}',
//     switchCategory:     'Canza Sashe',
//     allCategories:      'DUKKAN SASSA',
//     footerOrg:          '© Sashen Makarantar Lahadi Gospelar',
//     footerSite:         'www.gospelar.com',
//     selectCategory:     'ZAƁI SASHE',
//     darkMode:           '🌙  Yanayin Dare',
//     lightMode:          '☀️  Yanayin Haske',
//     // SecondPage
//     quarterlyUnits:     'Rukunoni na Watanni Uku',
//     unitsOfStudy:       'RUKUNONI NA KARATU',
//     tapToOpen:          'Taɓa don buɗewa  ›',
//     unitsFooter:        'Zaɓi rukuni don gano darasin sa.',
//     unitCount:          'Rukuni {n}',
//     // UnitLessonsPage
//     unitOfStudy:        'RUKUNI NA KARATU',
//     lessonsSection:     'DARASAI',
//     tapToStudy:         'Taɓa darasi don fara karatu.',
//     noLessons:          'Babu darasai ga wannan rukuni.',
//     lessonCount:        'Darasi {n}',
//     lessonCountPlural:  'Darasai {n}',
//     // LessonPage
//     lessonDetails:      'BAYANAN DARASI',
//     lesson:             'DARASI',
//     suggestedHymns:     'Waƙoƙin da Aka Ba da Shawara',
//     devotionalReading:  'Karatun Ibada',
//     adults:             'Manya',
//     youth:              'Matasa',
//     intermediate:       'Tsakiyar',
//     scriptures:         'Nassosi',
//     memoryVerse:        'ƘOFAR TUNAWA',
//     background:         'BAYAN BAYA',
//     notesOnLesson:      'BAYANIN DARASI',
//     conclusion:         'KAMMALAWA',
//     discussionQuestions:'TAMBAYOYIN TATTAUNAWA',
//     responsibilityMonth:'WATAN NAUYI',
//     quizFab:            'Jarrabawa',
//     dailyReading:       'Karatu\nna Yau',
//     // Quiz lock screen
//     quizLockedTitle:    'Come Back Tomorrow!',
//     quizLockedSub:      "You've already completed this quiz today.",
//     quizLockedRule:     'One attempt per lesson per day.',
//     gotIt:              'Got it',
//     noQuizBody:         'No questions found for this lesson yet.',
//     checkBackSoon:      'Check back soon!',
//     finishSubmit:       'Finish & Submit',
//     readFullScreen:     'Karanta Cikakken Allo',
//     partOf:             'Sashi {current} na {total}',
//     prev:               'Baya',
//     next:               'Gaba',
//     quizCompleted:      'Jarrabawa Ta Kare ✓',
//     takeQuiz:           'Yi Jarrabawa →',
//     loadingLesson:      'Ana lodi darasi…',
//     topicFor:           'Taken — {group}',
//     best:               'MAFI KYAU',
//     totalPts:           'JIMILAR MAKI',
//     yourRank:           'MATSAYINKA',
//     returnsIn:          'Zai dawo a',
//     todayScripture:     'NASSIN YAU',
//     verseInstruction:   'Karanta wannan sashe gaba ɗaya kafin fara ranar ka.\nNa\'am a kai tsaye da shi a duk rana kuma ɗauke shi tare da kai.',
//     highlightPrompt:    'Nuna Wannan',
//     removeHighlight:    'Cire Nuni',
//     removeMsg:          'Cire wannan nuni?',
//     highlightMsg:       'Nuna wannan sashe don sauƙin tunani.',
//     highlights:         'An Adana Alama {n}',
//     highlightsPlural:   'An Adana Alamomi {n}',
//     dayOf:              'Rana {current} na {total}',
//     devotionalDays:     'Ranakun Ibada',
//     prevDay:            'Baya',
//     nextDay:            'Gaba',
//     // Quiz lock
//     quizLockedTitle:    'Dawo Gobe!',
//     quizLockedSub:      'Kun kammala wannan jarrabawar yau.',
//     quizLockedRule:     'Ɗaya ƙoƙari a darasi ɗaya a rana.',
//     gotIt:              'Na Fahimta',
//     noQuizBody:         'Babu tambayoyi don wannan darasi.',
//     checkBackSoon:      'Dawo daga baya!',
//     finishSubmit:       'Kammala kuma Aika',
//     // Notifications
//     notificationsTitle:     'Sanarwa',
//     pushNotifications:      'Sanarwar Tunkude',
//     notifSubtitle:          "Zaɓi abin da za a tuna maka",
//     quizReminder:           'Tunawa da Jarrabawa',
//     quizReminderSub:        'Tunawa kowace rana don jarrabawar darasi',
//     devotionalReminder:     'Tunawa da Ibada',
//     devotionalReminderSub:  'Tunawa kowace rana don karatu na ibada na safe',
//     reminderTime:           'Lokacin Tunawa',
//     setTime:                'Saita Lokaci',
//     notifEnabled:           'An Kunna',
//     notifDisabled:          'An Kashe',
//     notifPermissionTitle:   'Kunna Sanarwa',
//     notifPermissionMsg:     'Bari Gospelar ya aiko maka tunatarwa kowace rana.',
//     notifPermissionDeny:    'Ba Yanzu',
//     notifPermissionAllow:   'Yarda',
//     notifSaved:             'An adana tunawa!',
//     notifCancelled:         'An kashe tunawa',
//     quizNotifTitle:         '⚡  Lokacin Jarrabawa!',
//     quizNotifBody:          'Kar ka manta yin jarrabawar darasi na yau. Ci gaba da kokari!',
//     devNotifTitle:          '📖  Ibada ta Yau',
//     devNotifBody:           "Fara ranarku da Maganar Allah. Karatu na ibada yana shirye.",
//     notifHour:              'Awa',
//     notifMinute:            'Minti',
//     notifAM:                'AM',
//     notifPM:                'PM',
//     // Homescreen & CombinedUnitsPage
//     quarterPeriod:      'LOKACIN KWATA',
//     memoryScripture:    'ƘOFAR TUNAWA',
//     browseUnits:        'Duba Sassan',
//     categories:         "Nau'o'i",
//     viewAll:            'Duba duka',
//     thisQuarter:        'Wannan Kwata',
//     searchPlaceholder:  'Nemo darussan, batutuwa…',
//     appearance:         'BAYYANAR',
//     language:           'HARSHE',
//     ageGroup:           'RUKUNI NA SHEKARU',
//     noUnits:            'Babu sassan da za a samu.',
//     unitsLabel:         'Sashi {n}',
//     unitsLabelPlural:   'Sassan {n}',
//     lessonsLabel:       'Darasi {n}',
//     lessonsLabelPlural: 'Darussan {n}',
//     browseAllLessons:   'Duba dukkan darussan',
//     // ProgressScreen
//     myProgress:          'Ci Gabana',
//     myScores:            'Makiyata',
//     leaderboard:         'Jerin Mafi Kyau',
//     lessonScores:        'Makiyata na Darasi',
//     topLearners:         'Manyan Masu Karatu',
//     cumulativeBest:      'Mafi kyawun makiyata jimilar',
//     noQuizzesYet:        'Babu jarrabawa har yanzu',
//     completeQuizToSee:   'Kammala jarrabawar darasi don ganin makiyata.',
//     startStudying:       'Fara Karatu',
//     noScoresYet:         'Babu makiyata har yanzu',
//     beFirstQuiz:         'Kasance na farko don kammala jarrabawa!',
//     home:                'Gida',
//     progress:            'Ci Gaba',
//     settings:            'Saiti',
//     lessons:             'Darussan',
//     read:                'Karanta',
//     saved:               'An Ajiye',
//     done:                'An Kammala',
//     points:              'Maki',
//     rank:                'Matsayi',
//     // Categories
//     cat_children:       'Yara',
//     cat_children_short: 'Yara',
//     cat_children_hero:  'Darussan nishaɗi\ndon ƙananan zukata\nna imani',
//     cat_children_cta:   'Fara Yanzu',
//     cat_children_tag:   'YARA',
//     cat_intermediate:   'Matsakaici',
//     cat_intermediate_short: 'Matsakaici',
//     cat_intermediate_hero: 'Gina tushe mai ƙarfi\ncikin Maganar Allah',
//     cat_intermediate_cta: 'Fara Karatu',
//     cat_intermediate_tag: 'MATSAKAICI',
//     cat_youth:          'Matasa',
//     cat_youth_short:    'Matasa',
//     cat_youth_hero:     'Shirya tsara mai zuwa\nna muminai',
//     cat_youth_cta:      'Shiga Yanzu',
//     cat_youth_tag:      'MATASA',
//     cat_adult:          'Manya',
//     cat_adult_short:    'Manya',
//     cat_adult_hero:     'Fara tafiyar ruhaniyarka\nba ta yanzu',
//     cat_adult_cta:      'Fara Darussan',
//     cat_adult_tag:      'MANYA',
//     cat_quarter:        'KWATA NA HUƊU • WA 4 – 8 2026',
//     cat_lessons13:      'Darussan 13',
//     quizCtaTitle:       'Yi Jarrabawar Darasi',
//     quizCtaSub:         'Gwada iliminka · sami maki · shiga jerin sunayen',
//     // Hymn Modal
//     suggestedHymnsTitle:'Waƙoƙin da Aka Ba da Shawara',
//     hymnsForLesson:     'Waƙa {n} don wannan darasi',
//     hymnsForLessonPlural:'Waƙoƙi {n} don wannan darasi',
//     hymnInstructions:   'Waƙoƙin nan suna ƙara wa taken darasi.',
//     tapToViewHymn:      'Taɓa don ganin waƙar',
//     hymnVerse:          '🎵  Rera wa Ubangiji sabuwar waƙa; rera wa Shi, dukkan ƙasa.',
//     hymnVerseRef:       '— Zabura 96:1',
//     // Devotional Modal
//     dailyDevotional:    'Ibada ta Yau',
//     devotionalBanner:   '"Maganarka fitila ce ga ƙafata, da haske ne ga hanyata."',
//     devotionalRef:      'Zabura 119:105',
//     // Quiz Modal
//     lessonQuiz:         'Jarrabawar Darasi',
//     loadingQuiz:        'Ana lodi tambayoyin jarrabawa…',
//     noQuizTitle:        'Babu Jarrabawa',
//     noQuizSub:          'Babu jarrabawa ga wannan darasi.\nKoma baya daga baya!',
//     questionOf:         'Tambaya {current} daga cikin {total}',
//     pts:                'Maki {n}',
//     nextQuestion:       'Tambaya Ta Gaba',
//     seeResults:         'Duba Sakamakon',
//     correctFeedback:    'Daidai! Kyakkyawan aiki.',
//     wrongFeedback:      'Amsar da ta dace: {letter}. {answer}',
//     scoreSaved:         'An adana makin ka!',
//     savingScore:        'Ana adana makin ka…',
//     saveError:          'Ba a iya adana makin ka.',
//     retryQuiz:          'Sake Jarrabawa',
//     done:               'Kammala',
//     excellent:          'Kyau Ƙwarai!',
//     wellDone:           'Kyakkyawan Aiki!',
//     keepStudying:       'Ci Gaba da Karatu!',
//     tryAgain:           'Sake Gwada!',
//     // DevotionalReadingScreen
//     openingPrayer:      'Addu\'ar Buɗewa',
//     reflection:         'Tunani',
//     application:        'Aiwatarwa',
//     highlighted:        'An Alama',
//     noHighlights:       'Taɓa sakin kowane a tsawo don alamar adana shi.',
//     savedHighlights:    'ALAMUN DA AKA ADANA',
//     clearAll:           'Share Duka',
//     cancel:             'Soke',
//     doHighlight:        '🖊  Alama',
//     doRemove:           '🗑  Cire',
//   },
// };

// // ─────────────────────────────────────────────────────────────────────────────
// const LanguageContext = createContext(null);

// const STORAGE_KEY = 'gofamint_lang';
// const VALID_LANGS = ['en', 'yo', 'ig', 'ha'];

// export function LanguageProvider({ children }) {
//   const getDict = useCallback(
//     (code) => TRANSLATIONS[code] || TRANSLATIONS.en,
//     [],
//   );

//   const [lang,         setLangState]   = useState('en');
//   const [translations, setTranslations] = useState(() => getDict('en'));
//   const [hydrated,     setHydrated]    = useState(false);

//   // ── Load persisted language on first mount ────────────────────────────────
//   useEffect(() => {
//     AsyncStorage.getItem(STORAGE_KEY)
//       .then(saved => {
//         if (saved && VALID_LANGS.includes(saved)) {
//           setLangState(saved);
//           setTranslations(getDict(saved));
//         }
//       })
//       .catch(() => {})
//       .finally(() => setHydrated(true));
//   }, []);

//   // ── Switch language — updates UI + persists choice ────────────────────────
//   const setLang = useCallback((langCode) => {
//     const resolved = VALID_LANGS.includes(langCode) ? langCode : 'en';
//     setLangState(resolved);
//     setTranslations(getDict(resolved));
//     AsyncStorage.setItem(STORAGE_KEY, resolved).catch(() => {});
//   }, [getDict]);

//   // ── No-op: category no longer auto-switches language ─────────────────────
//   const setLangFromCategory = useCallback(() => {}, []);

//   // ── t(key, vars) — translate with variable interpolation ─────────────────
//   // Always returns a real string — never a raw key name.
//   const t = useCallback((key, vars = {}) => {
//     let str = translations[key] ?? TRANSLATIONS.en[key] ?? key;
//     Object.entries(vars).forEach(([k, v]) => {
//       str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
//     });
//     return str;
//   }, [translations]);

//   // Don't render children until we've checked AsyncStorage so the app
//   // never flashes in the wrong language for a frame
//   if (!hydrated) return null;

//   return (
//     <LanguageContext.Provider value={{ lang, setLang, setLangFromCategory, t }}>
//       {children}
//     </LanguageContext.Provider>
//   );
// }

// export function useLanguage() {
//   const ctx = useContext(LanguageContext);
//   if (!ctx) throw new Error('useLanguage must be inside <LanguageProvider>');
//   return ctx;
// }




// context/LanguageContext.jsx
// ─────────────────────────────────────────────────────────────────────────────
// Language context — fetches UI translations from the server on every lang
// change and exposes a t(key, fallback?) function to any component.
//
// Flow:
//   1. On mount, load saved lang from AsyncStorage
//   2. Fetch translations from /api/translations/:langCode
//   3. Cache in AsyncStorage so the app works offline
//   4. t(key, fallback) returns the translated string or the English fallback
//
// Admin adds/edits strings via the Translations page in the admin dashboard.
// ─────────────────────────────────────────────────────────────────────────────

import React, {
  createContext, useContext, useState, useEffect, useCallback, useRef,
} from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { API_BASE_URL } from './SubscriptionContext';

// ── English baseline (always in-memory — never needs a server call) ───────────
// These are the keys used throughout the app. Admin can override any of them
// per language in the dashboard (Translations → add key → value in YO/IG/HA).
export const EN = {
  // ── Greeting ──────────────────────────────────────────────────────────────
  good_morning:         'Good morning',
  good_afternoon:       'Good afternoon',
  good_evening:         'Good evening',
  learner:              'Learner',
  health_tagline:       'Your learning journey continues today.',

  // ── Section titles ────────────────────────────────────────────────────────
  age_group:            'Age Group',
  recent_lessons:       'Recent Lessons',
  recently_visited:     'Recently Visited',
  quick_access:         'Quick Actions',
  view_all:             'View All →',
  start_quiz:           'Start Quiz',
  no_lessons:           'No lessons yet',
  loading:              'Loading…',

  // ── Quick access items ────────────────────────────────────────────────────
  notes:                'Notes',
  notes_sub:            'Your class notes',
  lessons:              'Lessons',
  lessons_sub:          'Browse all units',
  language:             'Language',
  language_sub:         'EN · YO · IG · HA',
  devotional:           'Devotional',
  devotional_sub:       'Daily reading plan',

  // ── Category labels ───────────────────────────────────────────────────────
  cat_adult:            'Adult',
  cat_youth:            'Youth',
  cat_intermediate:     'Intermediate',
  cat_children:         'Children',
  cat_adult_range:      '26 & above',
  cat_youth_range:      'Ages 18 – 25',
  cat_intermediate_range:'Ages 12 – 17',
  cat_children_range:   'Ages 4 – 11',

  // ── Tab bar ───────────────────────────────────────────────────────────────
  tab_home:             'Home',
  tab_lessons:          'Lessons',
  tab_notes:            'Notes',
  tab_settings:         'Settings',

  // ── Subscription / paywall ────────────────────────────────────────────────
  subscribe_title:      'Subscribe to Unlock',
  subscribe_sub:        'Choose a plan to access your lessons',
  plan_single:          'Single Category',
  plan_all:             'All Categories',
  plan_single_tagline:  'One age group of your choice',
  plan_all_tagline:     'Every age group unlocked',
  pay_now:              'Subscribe Now',
  select_plan:          'Select a plan above',
  select_category:      'Select a category above',
  pay_button:           'Pay',
  category_locked:      'Category Locked',
  category_locked_msg:  'Your plan only covers your selected category.',
  upgrade:              'Upgrade to All Categories',

  // ── Settings ──────────────────────────────────────────────────────────────
  settings:             'Settings',
  my_learning:          'My Learning',
  progress_scores:      'Progress & Scores',
  quiz_results:         'Quiz results and stats',
  lesson_library:       'Lesson Library',
  lesson_library_sub:   'Browse all Sunday School lessons',
  lang_label:           'Language',
  appearance:           'Appearance',
  dark_mode:            'Dark Mode',
  light_mode:           'Light Mode',
  switch_theme:         'Switch app theme',
  notifications:        'Notifications',
  account:              'Account',
  edit_profile:         'Edit Profile',
  edit_profile_sub:     'Name, avatar, church',
  change_password:      'Change Password',
  change_password_sub:  'Update your login password',
  sign_out:             'Sign Out',
  sign_out_sub:         'Sign out of this device',
  delete_account:       'Delete Account',
  delete_account_sub:   'Permanently remove data',
  about:                'About',
  about_app:            'About App',
  website:              'Website',
  reminderTime:         'REMINDER TIME',

  // ── Account screen ────────────────────────────────────────────────────────
  my_account:           'My Account',
  subscribed_category:  'Subscribed Category',
  subscription_details: 'Subscription Details',
  plan_type:            'Plan Type',
  status:               'Status',
  expires_on:           'Expires On',
  days_remaining:       'Days Remaining',
  active:               'Active',
  expired:              'Expired',
  renew:                'Renew Subscription',
  extend:               'Extend Subscription',
  your_plan:            'Your Plan',

  // ── Auto-injected app-wide UI keys ─────────────────────────────────
  about_app_info: 'APP INFORMATION',
  about_backend: 'BACKEND',
  about_built_with: 'BUILT WITH',
  about_contact: 'CONTACT',
  about_copyright: '© 2026 Gospelar Sunday School Department\nAll rights reserved.',
  about_dept: 'Sunday School Department',
  about_email: 'EMAIL',
  about_mission_body: 'Gospelar Sunday School is dedicated to providing quality, biblically-sound lessons that equip members of all ages for Christian living. Our app brings the Sunday School experience to your fingertips — anytime, anywhere.',
  about_our_mission: 'Our Mission',
  about_our_vision:  'Our Vision',
  about_vision_body: 'To raise a generation of believers grounded in scripture, equipped to live out their faith with confidence and conviction — and to make the depth of Sunday School teaching accessible to every member of our church family, in every language they speak, on every device they own.',
  about_released: 'RELEASED',
  about_tagline: 'Empowering believers through systematic Bible study and spiritual formation.',
  about_version: 'VERSION',
  about_website: 'WEBSITE',
  account_active_n_days: 'Active · {n} days remaining',
  account_active_one_day: 'Active · 1 day remaining',
  account_all_age_groups: 'All age groups',
  account_all_categories: 'All Categories',
  account_badge_500_plan: '₦500 Plan',
  account_badge_all_access: 'All Access',
  account_category: 'Category',
  account_email: 'Email',
  account_extend_sub: '{n} days left — top up now',
  account_full_access_note: 'Full access to all 4 age groups.',
  account_n_days: '{n} days',
  account_one_day: '1 day',
  account_renew_sub: 'Reactivate your access · from ₦500',
  account_signout_device: 'Sign Out of This Device',
  account_signout_msg: 'This will sign you out from this device. Your subscription stays active and can be restored by logging in again.',
  account_signout_note: 'Signing out removes local data only. Your subscription remains active and can be restored by logging in again.',
  account_single: 'Single',
  account_single_plan_note: 'Single category plan · Upgrade to unlock all.',
  account_sub_expired: 'Subscription expired',
  account_subscribe_now: 'Subscribe Now',
  account_subscribe_sub: 'From ₦500 · Choose your category',
  account_upgrade_label: 'Upgrade to All Categories',
  account_upgrade_sub: 'Unlock every age group · ₦1,000',
  account_zero_days: '0 days',
  btn_cancel: 'Cancel',
  btn_delete: 'Delete',
  btn_done: 'Done',
  btn_not_now: 'Not now',
  btn_ok: 'OK',
  btn_retry: 'Retry',
  btn_save: 'Save',
  bv_bible_tag: 'BIBLE',
  bv_could_not_load: 'Could not load verse.',
  bv_loading_ref: 'Loading {ref}…',
  bv_try_again: 'Try again',
  bv_verse_not_found: 'Verse not found',
  chpw_changed_msg: 'Your password has been updated successfully.',
  chpw_changed_title: '✅ Password Changed',
  chpw_confirm_label: 'CONFIRM PASSWORD',
  chpw_confirm_placeholder: 'Re-enter new password',
  chpw_confirm_required: 'Confirm your new password.',
  chpw_current_label: 'CURRENT PASSWORD',
  chpw_current_placeholder: 'Enter current password',
  chpw_current_required: 'Enter your current password.',
  chpw_failed: 'Failed.',
  chpw_info_card: '🔐  For your security, enter your current password first before setting a new one.',
  chpw_new_label: 'NEW PASSWORD',
  chpw_new_min: 'Must be at least 6 characters.',
  chpw_new_required: 'Enter a new password.',
  chpw_update_btn: 'Update Password  →',
  cunits_adult_class: 'Adult Class',
  cunits_book_philemon: 'Book of Philemon',
  cunits_browse_units: 'Browse Units →',
  cunits_childrens_class: 'Children\'s Class',
  cunits_coming_soon: 'Content may be coming soon.',
  cunits_daily_devotional: 'Daily Devotional',
  cunits_default_theme: 'Demonstration of the Christian Life',
  cunits_default_theme_sub: 'Exposition on the Book of Philemon',
  cunits_intermediate_class: 'Intermediate Class',
  cunits_lessons_in_unit: 'LESSONS IN THIS UNIT',
  cunits_loading_lessons: 'Loading lessons…',
  cunits_loading_units: 'Loading units…',
  cunits_no_lessons_in_unit: 'No lessons in this unit yet.',
  cunits_no_units_for: 'No units found for {label}.',
  cunits_stat_quarter: 'Quarter',
  cunits_stat_units: 'Units',
  cunits_subtitle_q4: 'Sunday School · Q4 2026',
  cunits_tab_units: 'Units',
  cunits_unit_n: 'Unit {n}',
  cunits_units_of_study: 'Units of Study',
  cunits_youth_class: 'Youth Class',
  delacc_confirm_password: 'CONFIRM YOUR PASSWORD',
  delacc_delete_btn: '🗑️  Delete My Account Forever',
  delacc_delete_forever: 'Delete Forever',
  delacc_deleted_msg: 'Your account has been permanently deleted.',
  delacc_deleted_title: 'Account Deleted',
  delacc_failed: 'Failed to delete account.',
  delacc_final_warning_msg: 'This will permanently delete your account, all quiz scores, and profile data. There is no way to recover this.',
  delacc_final_warning_title: '⚠️ Final Warning',
  delacc_irreversible: 'This action is irreversible',
  delacc_keep_account: 'Cancel — Keep My Account',
  delacc_not_logged_in: 'Not logged in.',
  delacc_password_placeholder: 'Enter your password to confirm',
  delacc_password_required: 'Please enter your password to confirm.',
  delacc_remove_intro: 'Deleting your account will permanently remove:',
  delacc_remove_item_1: '• Your account and login credentials',
  delacc_remove_item_2: '• All quiz scores and progress',
  delacc_remove_item_3: '• Your profile and preferences',
  delacc_remove_item_4: '• Your position on the leaderboard',
  dev_application: 'Application',
  dev_clear: 'Clear',
  dev_clear_hl_msg: 'Remove all?',
  dev_clear_hl_title: 'Clear Highlights',
  dev_daily_devotional: 'Daily Devotional',
  dev_daily_reading_caps: 'DAILY DEVOTIONAL READING',
  dev_devotional_content: 'Devotional Content',
  dev_highlight: 'Highlight',
  dev_highlighted_pill: '✎ Highlighted',
  dev_hl_section: 'Highlight Section',
  dev_long_press_to_hl: 'Long-press to highlight',
  dev_next: 'Next ›',
  dev_prayer: 'Prayer',
  dev_previous: '‹ Previous',
  dev_reflection: 'Reflection',
  dev_remove: 'Remove',
  dev_remove_hl: 'Remove Highlight',
  dev_remove_hl_q: 'Remove this highlight?',
  dev_save_section_q: 'Save this section?',
  dev_saved_highlights: 'Saved Highlights',
  dev_select_day: 'Select Day',
  dev_todays_reading: 'Today\'s Reading',
  err_network: 'Network error. Please check your connection.',
  fetch_failed_load: 'Failed to load data. Please check your connection and try again.',
  fetch_loading: 'Loading...',
  fetch_no_content: 'No content found.',
  fetch_something_wrong: 'Something went wrong',
  fetch_try_again: 'Try Again',
  guard_access_all_4: 'You now have access to all 4 categories!',
  guard_access_category: 'You now have access to the {label} category!',
  guard_access_granted: 'Access Granted! 🎉',
  guard_back_to_plans: '← Back to plans',
  guard_cannot_reach_server: 'Cannot Reach Server',
  guard_category_300: 'Category: {label} · 300 days',
  guard_check_connection: 'Check your internet connection and ensure the app server is running.',
  guard_checking_access: 'Checking your access…',
  guard_choose_category: 'Choose your category',
  guard_choose_category_sub: 'You\'ll only have access to this age group with the ₦500 plan',
  guard_choose_plan: 'Choose your plan',
  guard_choose_plan_sub: 'Select a subscription that works for you',
  guard_confirming_paystack: 'Confirming with Paystack…',
  guard_continue_with: 'Continue with {price}  →',
  guard_could_not_verify: 'We couldn\'t verify your payment. Please try again.',
  guard_days: 'days',
  guard_expires_today: 'Subscription expires today!',
  guard_feat_all_cats: 'All 4 categories',
  guard_feat_best_value: '🎁 Best value',
  guard_feat_devotionals: '📅 Daily devotionals',
  guard_feat_languages: '🌐 4-language support',
  guard_feat_one_cat: '1 category (your choice)',
  guard_feat_quizzes: '⚡ Lesson quizzes',
  guard_header_sub: 'Subscribe to unlock your content',
  guard_header_title: 'Gospelar Sunday School',
  guard_logout: '🚪  Log out',
  guard_n_days_left: '{n} days left — tap to renew',
  guard_one_day_left: '1 day left — tap to renew',
  guard_pay_format: 'Pay {price} — {label}  →',
  guard_payment_failed: 'Payment Failed',
  guard_renew_btn: 'Renew',
  guard_standard: 'Standard',
  guard_sub_activated: 'Subscription Activated!',
  guard_sub_active: 'Your subscription is now active',
  guard_tag_best_value: 'BEST VALUE',
  guard_tag_popular: 'POPULAR',
  guard_takes_few_seconds: 'This usually takes a few seconds.',
  guard_trust_instant: '⚡ Instant access',
  guard_trust_paystack: '🔒 Paystack secured',
  guard_try_again: 'Try Again',
  guard_try_again_msg: 'Please try again',
  guard_unlock_all_300: 'Unlocking all categories · 300 days',
  guard_verifying_payment: 'Verifying payment…',
  guard_verifying_your_payment: 'Verifying your payment…',
  guard_youll_access_prefix: 'You\'ll access ',
  guard_youll_access_suffix: ' content only',
  home_class_for: '{label} Class',
  home_good_day: 'Good day 👋',
  home_loading_lessons: 'Loading lessons…',
  home_locked_alert_msg: 'Your ₦500 plan only unlocks the {label} category. Upgrade to All Categories (₦1,000) to access {target}.',
  home_locked_pill: '🔒  Locked',
  home_no_recent: 'No recently visited lessons yet.',
  home_open_lesson_hint: 'Open a lesson and it will appear here.',
  home_recent_count_many: 'Showing your last {n} visited lessons',
  home_recent_count_one: 'Showing your last visited lesson',
  home_selected: 'Selected',
  home_start: 'Start →',
  home_subscribed: 'subscribed',
  hymn_chorus: 'CHORUS',
  hymn_could_not_connect: 'Could not connect to server. Check your network.',
  hymn_ghb_number: 'G.H.B. No. {n}',
  hymn_gospel_hymn_book: 'Gospel Hymn Book',
  hymn_intro_verse: 'Sing to the Lord a new song; sing to the Lord, all the earth. — Psalm 96:1',
  hymn_load_error: 'Could not load hymn',
  hymn_loading: 'Loading hymns…',
  hymn_next: 'Next →',
  hymn_no_n: 'No. {n}',
  hymn_not_found: 'Hymn not found',
  hymn_not_in_db: 'This number isn\'t in the database yet.',
  hymn_prev: '← Prev',
  hymn_verse_n: 'Verse {n}',
  lesson_background: 'Lesson Background',
  lesson_background_short: 'Background',
  lesson_conclusion: 'Lesson Conclusion',
  lesson_conclusion_short: 'Conclusion',
  lesson_daily_reading: 'Daily\nReading',
  lesson_discussion_questions: 'Discussion Questions',
  lesson_label: 'Lesson',
  lesson_label_caps: 'LESSON',
  lesson_loading: 'Loading lesson…',
  lesson_memory_verse: 'Memory Verse',
  lesson_next: 'Next ›',
  lesson_notes_on_lesson: 'Notes on the Lesson',
  lesson_overview: 'Lesson Overview',
  lesson_part_num: 'PART {n}',
  lesson_prev: '‹ Prev',
  lesson_quiz_completed: 'Quiz Completed',
  lesson_quiz_short: 'Quiz',
  lesson_read_fullscreen: 'Read Full Screen',
  lesson_start_quiz: 'Start Quiz',
  lesson_suggested_hymns: 'Suggested Hymns',
  lesson_take_quiz_sub: 'Earn points and track your progress',
  lesson_take_quiz_title: 'Take the Lesson Quiz',
  lesson_test_yourself: 'Test Yourself',
  lesson_view: 'View →',
  lesson_view_full_hymn: 'View Full Hymn',
  login_already_in_msg: 'This account is currently active on another device.\n\nContinuing will immediately log that device out.',
  login_already_in_title: '⚠️ Already Logged In',
  login_create_account: 'Create an account',
  login_email_invalid: 'Enter a valid email.',
  login_email_placeholder: 'Email address',
  login_email_required: 'Email is required.',
  login_failed: 'Login failed. Please try again.',
  login_footer: '© Gospelar Sunday School Department',
  login_forgot: 'Forgot password?',
  login_logout_other: 'Log Out Other Device',
  login_or: 'or',
  login_password_placeholder: 'Password',
  login_password_required: 'Password is required.',
  login_register: 'Register',
  login_reset_msg: 'Contact your administrator to reset your password.',
  login_reset_title: 'Reset Password',
  login_signin: 'Sign In',
  login_signin_btn: 'Sign In  →',
  login_sunday_school: 'Sunday School',
  login_welcome_back: 'Welcome back',
  login_welcome_sub: 'Sign in to continue your learning journey',
  notes_body_placeholder: 'Write what you learned in class today…',
  notes_class_notes: 'Class Notes',
  notes_delete: '🗑 Delete',
  notes_delete_confirm: 'Delete this note permanently?',
  notes_delete_title: 'Delete Note',
  notes_device_only: 'Notes are saved on this device only',
  notes_edit: '✏️ Edit',
  notes_edit_note: 'Edit Note',
  notes_empty_sub: 'Write down what you learn in class. Your notes are saved privately on this device.',
  notes_empty_title: 'No notes yet',
  notes_new_button: '+ New',
  notes_new_note: 'New Note',
  notes_no_match_sub: 'Try a different search term.',
  notes_no_match_title: 'No matching notes',
  notes_note: 'note',
  notes_notes: 'notes',
  notes_prefill_title: 'Notes — {lesson}',
  notes_save_note: 'Save Note',
  notes_search_placeholder: 'Search notes…',
  notes_stat_words: 'Words',
  notes_title_placeholder: 'Note title…',
  notes_untitled: 'Untitled Note',
  notes_update_note: 'Update Note',
  notes_word: 'word',
  notes_words: 'words',
  notes_write_first: 'Write Your First Note',
  pay_all_access: 'All Access',
  pay_all_cats_full: 'All Categories (Full Access)',
  pay_all_tagline: 'Access every age group',
  pay_back_arrow: '‹ Back',
  pay_change: 'Change',
  pay_choose_plan: 'CHOOSE YOUR PLAN',
  pay_continue_btn: 'Continue to Payment →',
  pay_days: 'days',
  pay_days_from_today: 'days from today',
  pay_email_help: 'Your subscription will be linked to this email. Use the same email to restore access on any device.',
  pay_email_invalid: 'Enter a valid email address.',
  pay_email_required: 'Please enter your email.',
  pay_enter_email_title: 'Enter Your Email',
  pay_err_no_category: 'Please select an age category for your plan.',
  pay_err_no_plan: 'Please choose a subscription plan.',
  pay_failed_title: 'Payment Failed',
  pay_feat_all_cats: 'All 4 categories',
  pay_feat_best_value: '🎁 Best value',
  pay_feat_devotionals: '📅 Daily devotionals',
  pay_feat_languages: '🌐 4-language support',
  pay_feat_one_cat: 'One category of your choice',
  pay_feat_quizzes: '⚡ Lesson quizzes',
  pay_hero_badge: '🔒  Secured by Paystack  ·  Instant Activation',
  pay_hero_sub: 'Sunday School · Digital Access',
  pay_only_suffix: 'Only',
  pay_opening_secure: 'Opening secure payment...',
  pay_proceed_btn: 'Proceed to Payment →',
  pay_row_category: 'Category',
  pay_row_email: 'Email',
  pay_row_expires: 'Expires',
  pay_row_plan: 'Plan',
  pay_row_standard: 'Standard',
  pay_secure_payment: 'Secure Payment',
  pay_select_age_category: 'SELECT YOUR AGE CATEGORY',
  pay_single_tagline: 'Access one age group',
  pay_success_note: 'The app will open automatically. Enjoy your studies! 🕊️',
  pay_success_sub: 'Your subscription is now active. Welcome to Gospelar Sunday School!',
  pay_success_title: 'Access Granted!',
  pay_tag_best_value: 'BEST VALUE',
  pay_tag_popular: 'POPULAR',
  pay_topbar_subscribe: 'Subscribe',
  pay_trust_instant: 'Instant Activation',
  pay_trust_paystack: 'Secured by Paystack',
  pay_try_again: 'Try Again',
  pay_verifying_sub: 'Please wait while we confirm your payment and activate your subscription.',
  pay_verifying_title: 'Verifying your payment...',
  profile_church_label: 'Church / Assembly',
  profile_church_placeholder: 'Church name',
  profile_could_not_save: 'Could not save.',
  profile_display_name: 'Display name',
  profile_edit: 'Edit',
  profile_location_label: 'Location',
  profile_location_placeholder: 'City, Country',
  profile_n_days_remaining: '{n} days remaining',
  profile_no_subscription: 'No active subscription',
  profile_not_set: 'Not set',
  profile_personal_info: 'PERSONAL INFO',
  profile_push_notifications: 'Push Notifications',
  profile_push_sub: 'Lesson reminders and updates',
  profile_save_failed: 'Save Failed',
  profile_subscription_status: 'Subscription Status',
  profile_title: 'Profile & Settings',
  profile_toggle_theme: 'Toggle app theme',
  progress_avg: 'avg',
  progress_be_first: 'Be the first to complete a quiz!',
  progress_best: 'Best',
  progress_complete_quiz_msg: 'Complete a lesson quiz to see your scores.',
  progress_completed: 'Completed',
  progress_cumulative_best: 'Cumulative best scores',
  progress_leaderboard: 'Leaderboard',
  progress_lesson_completed_one: 'lesson completed',
  progress_lesson_scores: 'Lesson Scores',
  progress_lessons_completed: 'lessons completed',
  progress_my_progress: 'My Progress',
  progress_my_scores: 'My Scores',
  progress_n_lessons_left: '{n} more lessons remaining — keep going!',
  progress_no_quizzes: 'No quizzes yet',
  progress_no_scores: 'No scores yet',
  progress_one_lesson_left: '1 more lesson remaining — keep going!',
  progress_points: 'Points',
  progress_rank: 'Rank',
  progress_start_studying: 'Start Studying',
  progress_tab_progress: 'Progress',
  progress_tab_quiz: 'Quiz',
  progress_tab_units: 'Units',
  progress_top_learners: 'Top Learners',
  progress_you_suffix: '(You)',
  quiz_answer_all_n: 'Answer all {n} questions',
  quiz_excellent: 'Excellent! 🎉',
  quiz_keep_studying: 'Keep studying! 💪',
  quiz_lesson_quiz: 'Lesson Quiz',
  quiz_loading: 'Loading questions…',
  quiz_n_of_total_answered: '{n} of {total} answered',
  quiz_no_questions: 'No quiz questions yet for this lesson.',
  quiz_pts: 'pts',
  quiz_q_label: 'Q',
  quiz_quiz_label: 'Quiz',
  quiz_score_format: '{score} / {max} points',
  quiz_submit_answers: 'Submit Answers →',
  quiz_well_done: 'Well done! ✓',
  register_btn: 'Create Account  →',
  register_coming_soon: 'Coming Soon',
  register_confirm_label: 'Confirm Password',
  register_confirm_placeholder: 'Re-enter password',
  register_confirm_required: 'Please confirm your password.',
  register_email_label: 'Email Address',
  register_email_placeholder: 'you@example.com',
  register_failed: 'Registration failed.',
  register_have_account: 'Already have an account?',
  register_i_am_a: 'I AM A',
  register_name_label: 'Full Name',
  register_name_placeholder: 'Your full name',
  register_name_required: 'Full name is required.',
  register_password_label: 'Password',
  register_password_min: 'Password must be at least 6 characters.',
  register_password_mismatch: 'Passwords do not match.',
  register_password_placeholder: 'Min. 6 characters',
  register_pw_fair: 'Fair',
  register_pw_good: 'Good',
  register_pw_strong: 'Strong',
  register_pw_weak: 'Weak',
  register_role_student: 'Student',
  register_role_teacher: 'Teacher',
  register_soon_suffix: '(Soon)',
  register_sub: 'Join thousands learning God\'s word daily',
  register_teacher_restricted: 'Teacher registration is currently restricted.',
  register_title: 'Create account',
  set_active_badge: 'ACTIVE',
  set_allow: 'Allow',
  set_currently_selected: 'Currently selected language',
  set_devotional_reminder: 'Devotional Reminder',
  set_disabled: 'Disabled',
  set_enable_notifications: 'Enable Notifications',
  set_enabled_at: 'Enabled · {time}',
  set_fixed: '🔒 Fixed',
  set_lang_english: 'English',
  set_lang_english_desc: 'Default app language',
  set_lang_hausa: 'Hausa',
  set_lang_hausa_desc: 'Northern Nigeria',
  set_lang_igbo: 'Igbo',
  set_lang_igbo_desc: 'South-east Nigeria',
  set_lang_yoruba: 'Yoruba',
  set_lang_yoruba_desc: 'South-west Nigeria',
  set_my_profile: 'My Profile',
  set_quiz_reminder: 'Sunday School Quiz Reminder',
  set_quiz_reminder_sub: 'Every Sunday · 3:00 PM · automatically scheduled',
  set_signout_confirm: 'Are you sure?',
  set_tap_allow_reminders: 'Tap to allow lesson reminders',
  set_version: 'Version 1.0.0 · Gospelar',
  teach_age_group_lbl: 'AGE GROUP',
  teach_attendance: 'Attendance',
  teach_class: 'Class',
  teach_class_caps: 'CLASS',
  teach_class_created_msg: 'Invite code: {code}\nShare this with your students.',
  teach_class_created_title: 'Class Created! 🎉',
  teach_class_name_lbl: 'CLASS NAME',
  teach_class_name_placeholder: 'e.g. Sunday Morning Adults',
  teach_class_name_required: 'Class name is required.',
  teach_classes: 'Classes',
  teach_classes_caps: 'CLASSES',
  teach_create_class_btn: 'Create Class',
  teach_create_first_class: 'Create First Class',
  teach_create_new_class: 'Create New Class',
  teach_dashboard_title: 'Teacher Dashboard',
  teach_description_lbl: 'DESCRIPTION (optional)',
  teach_description_placeholder: 'Brief description...',
  teach_error: 'Error',
  teach_hero_book: 'Manage classes · Mark attendance · Award points',
  teach_loading_classes: 'Loading classes…',
  teach_mark_attendance: 'Mark Attendance',
  teach_mark_attendance_sub: 'Record who was present today',
  teach_my_classes: 'My Classes',
  teach_new_class_btn: '+  New Class',
  teach_no_classes_msg: 'Create your first class and share the invite code with your students.',
  teach_no_classes_yet: 'No classes yet',
  teach_progress: 'Progress',
  teach_students_caps: 'STUDENTS',
  teach_students_lbl: 'students',
  teach_tab_attend: 'Attend',
  teach_tab_classes: 'Classes',
  teach_tab_progress: 'Progress',
  teach_teacher_default: 'Teacher',
  teach_teacher_tag: 'TEACHER',
  teach_teacher_tools: '📋  TEACHER TOOLS',
  teach_view_progress: 'View Progress',
  teach_view_progress_sub: 'Leaderboard & attendance heatmap',
  teach_welcome_back: 'Welcome back,',
  tmark_absent: 'Absent',
  tmark_answered_question: 'Answered Question',
  tmark_bonus_points: 'Bonus Points',
  tmark_memory_verse: 'Memory Verse',
  tmark_present: '✓ Present',
  tmark_pts_awarded: '+{n} pts awarded',
  unit_n_lessons: '{n} Lessons',
  unit_one_lesson: '1 Lesson',
  units_count: '{n} Units',
  units_quarter_period: '4TH QUARTER  •  JUNE – AUG 2023',
  units_theme_main: 'CHRISTIAN LIFE',
  units_theme_prefix: 'Demonstration of the',
  units_theme_sub: 'EXPOSITION ON THE BOOK OF PHILEMON',

  // ── Homescreen banner titles (passed via variable, missed by static extract)
  home_banner_quarter_title:     'Q4 2026 Quarter',
  home_banner_quarter_sub:       'Exposition on Philemon',
  home_banner_devotionals_title: 'Daily Devotionals',
  home_banner_devotionals_sub:   'Read & grow each morning',
  home_banner_quiz_title:        'Quiz Challenge',
  home_banner_quiz_sub:          'Earn points this week',
  home_banner_leaderboard_title: 'Leaderboard',
  home_banner_leaderboard_sub:   'See where you rank',
};

// ─────────────────────────────────────────────────────────────────────────────
const LanguageContext = createContext({
  lang:    'en',
  setLang: () => {},
  t:       (key) => EN[key] || key,
  translations: {},
  loading: false,
});

export const useLanguage = () => useContext(LanguageContext);

export function LanguageProvider({ children }) {
  const [lang,         setLangState]  = useState('en');
  const [translations, setTrans]      = useState({});  // { key: value } for current lang
  const [loading,      setLoading]    = useState(false);
  const cache = useRef({});   // in-memory cache keyed by lang code

  // ── Load saved lang on mount ─────────────────────────────────────────────
  useEffect(() => {
    AsyncStorage.getItem('app_lang').then(saved => {
      if (saved && saved !== 'en') fetchTranslations(saved, true);
      else setLangState('en');
    }).catch(() => {});
  }, []);

  // ── Fetch translations from server (or memory/disk cache) ────────────────
  const fetchTranslations = useCallback(async (code, skipSave = false) => {
    if (code === 'en') {
      setLangState('en');
      setTrans({});
      return;
    }

    // Use in-memory cache first (instant)
    if (cache.current[code]) {
      setLangState(code);
      setTrans(cache.current[code]);
      return;
    }

    // Try disk cache (works offline)
    try {
      const cached = await AsyncStorage.getItem(`trans_cache_${code}`);
      if (cached) {
        const parsed = JSON.parse(cached);
        cache.current[code] = parsed;
        setLangState(code);
        setTrans(parsed);
        // Still fetch fresh in background
        refreshFromServer(code);
        return;
      }
    } catch {}

    // Fresh server fetch
    setLoading(true);
    await refreshFromServer(code);
    setLangState(code);
    setLoading(false);
  }, []);

  const refreshFromServer = async (code) => {
    try {
      const res  = await fetch(`${API_BASE_URL}/api/translations/${code}`);
      const data = await res.json();
      const map  = data.translations || {};
      cache.current[code] = map;
      setTrans(map);
      // Persist to disk
      await AsyncStorage.setItem(`trans_cache_${code}`, JSON.stringify(map));
    } catch {
      // Network error — keep whatever is in state already
    }
  };

  // ── Public setLang ───────────────────────────────────────────────────────
  const setLang = useCallback(async (code) => {
    await AsyncStorage.setItem('app_lang', code);
    await fetchTranslations(code);
  }, [fetchTranslations]);

  // ── t(key, fallback?) ────────────────────────────────────────────────────
  // Priority: server translation → English baseline → key itself
  const t = useCallback((key, fallback) => {
    if (lang !== 'en' && translations[key]) return translations[key];
    return EN[key] ?? fallback ?? key;
  }, [lang, translations]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, translations, loading }}>
      {children}
    </LanguageContext.Provider>
  );
}